### ISSUE TITLE
Cannot craft Alchemical Construct in Miniaturization Field.

### ISSUE THREAD

**Issue by johnll56** [Filostorm/Multiblock-Madness#105]
Hey Filo. Trying to craft the AC as shown in JEI, but nothing is happening after throwing in the Dawnstone Gear. Attached pic for reference. I have also tried with the essentia valve at the top pointing into the greatwood plank, but no result either. Haven't reached 3D Crafter yet so can't test it there.
Thanks and happy new years!
![2022-01-01_21 56 04](https://user-images.githubusercontent.com/74071241/147863440-5d055aac-9385-4e5a-b20a-142ab2ec270b.png)

**Comment by johnll56** [comment]
Hey Filo. Trying to craft the AC as shown in JEI, but nothing is happening after throwing in the Dawnstone Gear. Attached pic for reference. I have also tried with the essentia valve at the top pointing into the greatwood plank, but no result either. Haven't reached 3D Crafter yet so can't test it there. 
Thanks!
![2022-01-01_21 56 04](https://user-images.githubusercontent.com/74071241/147863428-683a49a8-31f7-4ee3-8eec-f79065de5b70.png)

**Comment by lawfulrocky** [comment]
i think the valves are turn the wrong way on the sides

**Comment by lawfulrocky** [comment]
and bottom

**Comment by Filostorm** [comment]
You need an additional 4 pipes between the steel sheetmetal. 

Thanks and happy New Years to you as well!

**Comment by johnll56** [comment]
> You need an additional 4 pipes between the steel sheetmetal.
> 
> Thanks and happy New Years to you as well!

Ohh. I'm dumb. Thank you!

**Comment by johnll56** [comment]
> You need an additional 4 pipes between the steel sheetmetal.
> 
> Thanks and happy New Years to you as well!

Ohh I'm dumb. Thanks so much!
