### ISSUE TITLE
Problem with crafting Runic matrix

### ISSUE THREAD

**Issue by Vateg** [Filostorm/Multiblock-Madness#107]
I tried to make this craft 3 times, but I constantly got just a ghost block, what am I doing wrong?
![image](https://user-images.githubusercontent.com/97977697/149995563-2e3ad92c-4b96-427d-b836-3c721f4f6f16.png)

**Comment by Filostorm** [comment]
What version and are you on a server?

**Comment by Vateg** [comment]
1.2.1

**Comment by Vateg** [comment]
Server

**Comment by Filostorm** [comment]
For some reason the 5x5 field is bugged in that release, build it in a 7x7.

**Comment by Vateg** [comment]
ok thanks you

**Comment by Vateg** [comment]
nothing works anyway, ghost block again... :((

**Comment by Vateg** [comment]
I don't have the patience to play this modpack anymore, there are only bugs everywhere, I already spent a lot of resources to make this runic matrix, and I didn't get anything

**Comment by Filostorm** [comment]
In case you didn't know, you're playing on a very much outdated version of the pack. That bug and probably every other bug you've run into is fixed already

**Comment by Vateg** [comment]
I'm not the creator of the sevrer, even if I ask the creator to update the modpack to a new version, he won't do it :(

**Comment by Filostorm** [comment]
Ah, that's unfortunate.
