### ISSUE TITLE
Bronze is required to create the Embers Centrifuge?

### ISSUE THREAD

**Issue by Phantom914** [Filostorm/Multiblock-Madness#11]
How is Bronze obtained? I looked at every JEI recipe and it seems like the Embers Centrifuge is the next step for bronze, except bronze is needed to make it, so that doesn't make sense.

**Comment by Filostorm** [comment]
Via the Smeltery

**Comment by Phantom914** [comment]
Ok, I got it, had to do the Astral Sorcery stuff
