### ISSUE TITLE
Quest Error

### ISSUE THREAD

**Issue by Shengxiaomoyu-ForesT** [Filostorm/Multiblock-Madness#113]
I cannot finish my all quest whether I update my questbook and when I update my quest book, my quest show the all quests are unfinished. But it is certainly impossible. It may because I change my launcher. 
![BEF`8P70`E_7LW1H~YYH$(V](https://user-images.githubusercontent.com/76878130/153717096-41b03eff-3a71-4d55-9e3f-29d708016b50.png)

![0J3PQUD8Q3}`RM88CHTS %M](https://user-images.githubusercontent.com/76878130/153717093-e415470e-8cc7-409f-b323-1dc1674256d6.png)
pls help me.thx

**Comment by Filostorm** [comment]
If you are able to run commands, you can manually complete quests. Use /bq_admin edit, then follow these pictures

![2022-02-12_13 10 46](https://user-images.githubusercontent.com/73716145/153723032-dcb3cfb5-3ee4-4b58-89b5-576ae07e3ddb.png)
![2022-02-12_13 10 51](https://user-images.githubusercontent.com/73716145/153723033-92482058-3959-417f-b0d1-7f83364f58c0.png)

**Comment by Shengxiaomoyu-ForesT** [comment]
I cannot complete quests by such way although I had follow the ways like pictures but it have no changes.
