### ISSUE TITLE
Suggestion - add Rockhounding Chemistry-Core to Morph-o-Tool Mod Aliases

### ISSUE THREAD

**Issue by anabsolutesloth** [Filostorm/Multiblock-Madness#114]
Would let the Morph-o-Tool autoconvert into the Rockhounding Core wrench when looking at Rockhounding Chemistry blocks.

`rockhounding_chemistry=rockhounding_core`

**Comment by Filostorm** [comment]
Done

**Comment by Filostorm** [comment]
Actually added this now lol
