### ISSUE TITLE
MBM3.0.0 [Blood Magic] 

### ISSUE THREAD

**Issue by Q3697** [Filostorm/Multiblock-Madness#116]
[Blood Altar]  Unable to build third floor
![Screenshot 2022-02-27 094227](https://user-images.githubusercontent.com/100544063/155908610-0983bc93-4a62-422f-9029-c5c928e95544.png)
Translate:The Altar of Blood on the next floor is missing a glowstone block.

**Comment by Filostorm** [comment]
You need to use Primal Voidstone Eye for the tier 3 caps

**Comment by Q3697** [comment]
Thank you .
