### ISSUE TITLE
Astral Sorcery Luminous Crafting Table Recipe doesn't craft

### ISSUE THREAD

**Issue by Phantom914** [Filostorm/Multiblock-Madness#12]
I tried inputting the blocks required for the Luminous Crafting Table, but there's no item output on crafting table when I put the recipe in manually or with JEI

**Comment by lawfulrocky** [comment]
You have to right click the table with the resonate wand from Astral with enough starlight

**Comment by Filostorm** [comment]
The most likely case is you need more starlight, which you can get by adding a relay or moving into a starlight rich area. You can find those with the Fosnic Resonator

**Comment by Phantom914** [comment]
Ok, yes my bad. I have only played half the mods on here. I looked up a tutorial. Luckily there was a big shrine right near me
