### ISSUE TITLE
Actually Additions Farmer crashes the game

### ISSUE THREAD

**Issue by MLellmann** [Filostorm/Multiblock-Madness#121]
I tried to use the Actually Additions Farmer to plant Canola Seeds on plain farm land, and the moment I put a seed into it, the game crashed. It continued crashing after loading the world again, or repeating that process in a new world.

[crash-2022-04-14_20.28.20-server.txt](https://github.com/Filostorm/Multiblock-Madness/files/8495290/crash-2022-04-14_20.28.20-server.txt)

The issue seems to be with the mod ThaumicAdditionsAgricraftCompat as disabling it will remove the crash.

This happened in Multiblock Madness Version 3.0.3.

**Comment by thibaut-fagart** [comment]
i'm facing the same issue

**Comment by IanMcC99** [comment]
Marking for replication (Ian-Staff)

**Comment by IanMcC99** [comment]
Please reply with pack version, and any other mods added to your instance.

**Comment by IanMcC99** [comment]
Issue fixed in 3.0.5, please upgrade your pack to resolve issue. Marking as closed.
