### ISSUE TITLE
screen issue

### ISSUE THREAD

**Issue by Superbaker8** [Filostorm/Multiblock-Madness#123]
Hello, every time I log in to my server the screen goes black but i can still break things or kill entities or log off the server.

**Comment by Filostorm** [comment]
What version, and have you added any mods?

**Comment by Superbaker8** [comment]
> What version, and have you added any mods?

I am in 3.0.5 and I just added optifine 1.12.2

**Comment by Filostorm** [comment]
Try without Optifine and let me know if that works
