### ISSUE TITLE
Quest issue

### ISSUE THREAD

**Issue by Superbaker8** [Filostorm/Multiblock-Madness#124]
hello, this quest is the lastest in chaper 3 but it require a machine in the late chapter 4, so if there is another way of doing it hope someone tell me 
![2022-05-15_15 11 28](https://user-images.githubusercontent.com/105354898/168472228-fe3a25ce-c255-44da-82c3-b9aea15c72ad.png)
![2022-05-15_15 11 31](https://user-images.githubusercontent.com/105354898/168472239-94a8d432-bb03-47ae-bee6-8414ef0a3aae.png)
![2022-05-15_15 11 38](https://user-images.githubusercontent.com/105354898/168472245-9a870206-a732-40ab-ad9c-8890c21af932.png)
![2022-05-15_15 11 42](https://user-images.githubusercontent.com/105354898/168472251-17056e23-5f88-4e43-8574-bcbce8f7a04c.png)
![2022-05-15_15 12 02](https://user-images.githubusercontent.com/105354898/168472254-5f91c44a-4a12-483a-9bc0-c5e57a68b422.png)

**Comment by Filostorm** [comment]
Yep, that's supposed to have a casting recipe. Ty

**Comment by Filostorm** [comment]
Fixed in 3.1.0
