### ISSUE TITLE
Advanced Coke Oven issue

### ISSUE THREAD

**Issue by Kyuuragi** [Filostorm/Multiblock-Madness#127]
The reinforced coke bricks don't seem to be recognized by the morphing tool for swapping to the IE hammer, and even when properly built, the multiblock refuses to form.

**Comment by Filostorm** [comment]
The advanced coke oven no longer exists in Immersive Tech

**Comment by Kyuuragi** [comment]
Interesting, I wonder why the advanced coke bricks are still craftable then.

Though I'm having the same issue with the Distilling tower not forming as well



Sent from my Galaxy



-------- Original message --------
From: Filostorm ***@***.***>
Date: 2022-05-22 4:05 p.m. (GMT-08:00)
To: Filostorm/Multiblock-Madness ***@***.***>
Cc: Kyuuragi ***@***.***>, Author ***@***.***>
Subject: Re: [Filostorm/Multiblock-Madness] Advanced Coke Oven issue (Issue #127)


The advanced coke oven no longer exists in Immersive Tech

**Comment by Kyuuragi** [comment]
Structure is built as shown in the IE manual, so seemingly no issues on that front, but the multi block won't assemble.

Tried using the capsule from the quest reward as well, but strangely - though the capsule icon changes to loaded -, attempting to use the capsule neither consumes the items from my inventory, nor comes up with a preview for the tower in the world.

The blue outlines marking the area of the structure appear, but nothing for the structure itself.






-------- Original message --------
From: Filostorm ***@***.***>
Date: 2022-05-22 6:19 p.m. (GMT-08:00)
To: Filostorm/Multiblock-Madness ***@***.***>
Cc: Kyuuragi ***@***.***>, Author ***@***.***>
Subject: Re: [Filostorm/Multiblock-Madness] Advanced Coke Oven issue (Issue #127)


That's a good point, I'll consider removing them.

The Tower has no issues I know of, can you double check the structure?

**Comment by Kyuuragi** [comment]
In case it matters, I just updated the pack to 3.1.0, uncertain if that may be aa part of the issue

**Comment by Kyuuragi** [comment]
Crafted a new Engineer's Hammer to test, no change.

**Comment by Filostorm** [comment]
Is that the only multiblock that's  not forming?

**Comment by shawn1368** [comment]
I've tested out forming the distillation tower on the latest version of the modpack and it works fine. Try right clicking the redstone engineering block with the engineer's hammer.

**Comment by Kyuuragi** [comment]
Seems to be working now, not sure what the issue ended up being in the end
