### ISSUE TITLE
Recipe issue (Quest)

### ISSUE THREAD

**Issue by Superbaker8** [Filostorm/Multiblock-Madness#129]
Hello, just a question , How can i make the diesel generator without having an arc furnance? .
![2022-05-25_22 42 05](https://user-images.githubusercontent.com/105354898/170354436-39d4b4bf-dc45-493e-9096-c8fb8d04f487.png)
![2022-05-25_22 42 11](https://user-images.githubusercontent.com/105354898/170354446-f5e0694f-b227-4d83-91eb-ed70800061b1.png)
![2022-05-25_22 42 21](https://user-images.githubusercontent.com/105354898/170354457-da0d303c-af42-4b52-a755-fbb91c2c8868.png)
![2022-05-25_22 43 47](https://user-images.githubusercontent.com/105354898/170354463-43af7e6f-0517-4fc3-b701-e44421946d5e.png)

**Comment by Filostorm** [comment]
There is a casting table recipe involving Gasoline.

**Comment by Superbaker8** [comment]
yup thx just saw it
