### ISSUE TITLE
No recipe for Tech Reborn's Iron Furnace

### ISSUE THREAD

**Issue by iasazo** [Filostorm/Multiblock-Madness#13]
Tech Reborn's 'Iron Furnace' is used in the recipe for Ember's 'Melter'.  Was it intended for the recipe to use the 'Iron Furnace' from More Furnaces?

**Comment by Phantom914** [comment]
It's a known crafting tweak error. I ended up fixing it myself temporarily because the new version hasn't been released yet

**Comment by Filostorm** [comment]
Correct, the update that fixes it is out as of last night
