### ISSUE TITLE
Blood magic tier 3

### ISSUE THREAD

**Issue by ShinyBoy69** [Filostorm/Multiblock-Madness#130]
I'm trying to build the tier 3 blood magic altar, and it keeps telling me that I'm missing a glowstone + in the book in it's telling me to place 20 rune blank and void stone, but it's not saying where should I use the void stone at

**Comment by Filostorm** [comment]
The Voidstone goes on top of the pillars as a replacement for glowstone.

**Comment by shawn1368** [comment]
If you want more direct help with the modpack, you can consider joining the MBM discord (link in the README).
