### ISSUE TITLE
Recipe issue

### ISSUE THREAD

**Issue by Superbaker8** [Filostorm/Multiblock-Madness#131]
Hello, how can i make the Master ritual stone, I do have all the stuff to make it, but I can't make it with apprentice blood orb, do i need to make another one because there is nothing in the quests that says that i need
![2022-05-27_06 20 41](https://user-images.githubusercontent.com/105354898/170622775-af86bc5d-2366-411e-8083-21416a79ef2e.png)
![2022-05-27_06 20 46](https://user-images.githubusercontent.com/105354898/170622784-8f54374f-b811-4622-ac7d-fd8164892457.png)
![2022-05-27_06 20 50](https://user-images.githubusercontent.com/105354898/170622788-04bfec1f-0359-4b5a-b6e6-1f49b876ccfe.png)
.

**Comment by shawn1368** [comment]
The BM Rituals quest will be moved over to ch5 behind the magician orb, in accordance to the master ritual stone's recipe which requires a magician orb, in the next update.
