### ISSUE TITLE
Data storage circuit

### ISSUE THREAD

**Issue by ShinyBoy69** [Filostorm/Multiblock-Madness#132]
To make the data storage circuit I need 8000 FE/t in total 800000 FE how could I produce that much of energy  plus it keeps taking the items, and then it would say there isn't enough energy

**Comment by shawn1368** [comment]
Modular machinery machines will consume the items before beginning the recipe, so you need to make sure that you have enough power before starting the recipe.

If you're making data circuits already, you should be around early-mid ch5, which means you have access to the diesel generator or advanced generators turbine. I'd recommend going for the diesel generator if you haven't already, or the AG turbine if you can to solve your power woes.

For more questions and more direct help, I'd strongly recommend joining the MBM discord at https://discord.gg/YQ8jpvKA, where you can get more help and tips and tricks from other people also playing the pack. Try to keep gameplay questions on the github to a minimum, as it's meant to track issues with the modpack.
