### ISSUE TITLE
2000 heat

### ISSUE THREAD

**Issue by ShinyBoy69** [Filostorm/Multiblock-Madness#133]
In the industrial blast furnace I need 2000 heat to melt platinum how can I increase the heat FYI I already have 2 lava buckets

**Comment by anabsolutesloth** [comment]
Dude, go to the discord for questions, generally Github issue tabs are used for actual technical issues, like Crashes or Recipes not being right, or just stuff being broken in general.

here is literally the link: https://discord.gg/qfEAtfY
go, don't clog up githubs with issues that people can answer on like, forums and discord servers.
