### ISSUE TITLE
Pumpjack problem 

### ISSUE THREAD

**Issue by Superbaker8** [Filostorm/Multiblock-Madness#134]
just a question is there anything wrong with the pumpjacks because I always get a problem which is that one of my pumpjacks just stops working even though the other ones are working.

**Comment by shawn1368** [comment]
Could you provide more information on this? 

- Where is the pumpjack located?
- How is it being powered? Does your base have enough power to power the pumpjacks?
- Do you have another pumpjack in the same chunk?

My hunch is that you have 2 pumpjacks in the same chunk that has been depleted of oil, leading to one of them not working.

**Comment by Superbaker8** [comment]
> Could you provide more information on this?
> 
>     * Where is the pumpjack located?
> 
>     * How is it being powered? Does your base have enough power to power the pumpjacks?
> 
>     * Do you have another pumpjack in the same chunk?
> 
> 
> My hunch is that you have 2 pumpjacks in the same chunk that has been depleted of oil, leading to one of them not working.

yup I had 2 pumpjacks in the same chunk, I didn't know that, thank you
