### ISSUE TITLE
Embers mini boilers don't produce any steam

### ISSUE THREAD

**Issue by abralcor33** [Filostorm/Multiblock-Madness#149]
Hi, I started the mod-pack few days ago, so with last update.
I didn't manage to make mini-boilers producing steam. I can see they're plenty full of water but the third buffer stays empty.
I've tried to attach the mini-boiler to a melter, to an ember activator fully running but no result

**Comment by Filostorm** [comment]
Odds are you have the boiler attached to the top of the machine. It needs to be attached to the bottom block on the side

**Comment by abralcor33** [comment]
I've tried the bottom and top both

**Comment by abralcor33** [comment]
oh... OK I didn't tried the bottom block of the melter.. my bad.
It works. thanks a lot. Sorry for bothering.
