### ISSUE TITLE
Pillaring doesnt work

### ISSUE THREAD

**Issue by Peach774** [Filostorm/Multiblock-Madness#15]
The technique where you jump and place a block directly beneath you by holding space and right click doesnt work. it works for a block or two and then it stops placing the blocks, as if im not high up enough.

**Comment by Filostorm** [comment]
Unfortunately this is a known bug, and one I don’t know the cause of. Spam placing the blocks instead of holding down seems to work for now though.

**Comment by Filostorm** [comment]
Fixed! Performant was the cause, and will be removed in the next update.
