### ISSUE TITLE
Ultimate Stew Recipe is duplicated

### ISSUE THREAD

**Issue by JohanniklasLp** [Filostorm/Multiblock-Madness#152]
![grafik](https://user-images.githubusercontent.com/57828910/183886833-6672ba92-ff3d-446c-93ce-a4fbf6c339e6.png)
![grafik](https://user-images.githubusercontent.com/57828910/183886856-19d50e34-5ebd-43c6-a57c-fb98f71f42e3.png)
Two pages with the same recipe on both of them

**Comment by shawn1368** [comment]
Fixed in next update
