### ISSUE TITLE
Quest book not working

### ISSUE THREAD

**Issue by CrystalDiamondia** [Filostorm/Multiblock-Madness#156]
For some reason, my quest book doesn't work at all. Pressing the Detect/Submit button doesn't detect the items, even if I have them in my inventory.

I've tried completing the quest it got stuck on (heavy engineering blocks) with commands, but it doesn't work. I've even tried resetting the quest book in its entirety, and it does not work.

I'm using version 3.2.0.

**Comment by CrystalDiamondia** [comment]
Also, all of my advancements seem to have reset and my skin is back to the default Steve. That might be connected to that.

**Comment by CrystalDiamondia** [comment]
All of my set homes have been reset, as well.

**Comment by Filostorm** [comment]
Sounds like your player data got deleted somehow
