### ISSUE TITLE
World crash with IT Distillation Tower capsule

### ISSUE THREAD

**Issue by BlazeHunterVN1610** [Filostorm/Multiblock-Madness#171]
When you craft the Distillation Tower capsule, a bunch of error line appear in chat:
![2023-03-31_17 07 52](https://user-images.githubusercontent.com/111768452/229092162-19280059-d882-46ce-b8f0-ac3b7804d824.png)
If you put the capsule that you crafted into the inventory, the game immedietely crash
The capsule in JEI doesn't crash the game when inside the inventory
Edit:
The crafted capsule can't deploy the multiblock:
![2023-03-31_17 26 24](https://user-images.githubusercontent.com/111768452/229095739-0f5b7fb2-6ff3-4b9c-9350-f53822292603.png)
The JEI capsule can deploy, but cannot undo:
![2023-03-31_17 27 46](https://user-images.githubusercontent.com/111768452/229096018-50c23a76-2990-487b-ae18-864fd7431549.png)
The crafted capsule's doesn't have steel scaffolding slab in requirement:
![2023-03-31_17 35 46](https://user-images.githubusercontent.com/111768452/229097803-d847851d-7e96-4046-93d6-929421563964.png)
JEI capsule has normal requirement:
![2023-03-31_17 36 42](https://user-images.githubusercontent.com/111768452/229097930-8cfcda23-fd1a-46ed-8a97-22f2b7ac36b6.png)
Also, the capsule that the quest give is unusable, and has spelling error:
![2023-03-31_17 39 22](https://user-images.githubusercontent.com/111768452/229098572-9f128a4c-5d42-4687-a060-49d30b3dedb8.png)

**Comment by shawn1368** [comment]
It seems that it is not possible for crafted blueprints to contain slabs. However, the quest has been fixed to contain the original capsule which seems to work with slabs just fine in 3.2.2, so it shouldn't be a problem for people using the quest reward's blueprint.
