### ISSUE TITLE
modpack wont load

### ISSUE THREAD

**Issue by Furnaced** [Filostorm/Multiblock-Madness#181]

**Comment by Filostorm** [comment]
How much ram do you have allocated, and what's your total ram? 

Also send the log file

**Comment by Furnaced** [comment]
10 g allocated and 16 g total

[latest.log](https://github.com/Filostorm/Multiblock-Madness/files/13198248/latest.log)

**Comment by Filostorm** [comment]
Launcher?

**Comment by Furnaced** [comment]
ftb app launcher

**Comment by Filostorm** [comment]
Hmm, not really sure what's the issue then. You could try dropping down to 8 gb, but it really shouldn't matter. It might just take extra time on first load

**Comment by Furnaced** [comment]
ok thanks
