### ISSUE TITLE
Various Rockhounding Problems

### ISSUE THREAD

**Issue by m-yst-ery** [Filostorm/Multiblock-Madness#183]
It seems like the currently used version of Rockhounding has multiple problems - or at least for me.

1) Cannot pick fluids in the Fluidpedia.
Besides the UI being broken (which I assume is meant by what the quest says) I also cannot pick any fluid filters in it.
This isn't that big of an issue if you actually don't need more filters than Brine and Water, but I'm not sure about that since I haven't gotten much further because...

2) The Metal Alloyer seems to be completely non-functional
![image](https://github.com/Filostorm/Multiblock-Madness/assets/111455503/23a54915-d623-4534-860a-bcb54c29cbe7)
Here's my setup incase it is an error on my end
![image](https://github.com/Filostorm/Multiblock-Madness/assets/111455503/d9bf0298-a594-4cb4-8e3f-e0901948e170)
In the UI the tooltip where it should say what is needed for a recipe doesn't show and it also just doesn't craft anything, which are likely related issues.

When I first discovered the problem with the Fluidpedia a few days ago I did test updating Rockhounding by hand, which did fix that problem but obviously broke all the custom stuff in this modpack. I haven't tested it for the metal alloyer though.

**Comment by Filostorm** [comment]
Looks like you have your server active (blue button on the top left of the UI). That could probably be disabled. Also make sure you have a graduated cylinder in both of your cabinets.

**Comment by m-yst-ery** [comment]
I have also tried it with the server disabled and not attached, but the behaviour was the same.
Both cabinets have a graduated cylinder in them.

**Comment by Filostorm** [comment]
Can you show the power station gui and make sure the cabinets are in the correct order?

**Comment by m-yst-ery** [comment]
Because the gif is to big to post it directly: [https://imgur.com/a/OfTDlck](https://imgur.com/a/OfTDlck)
I hope this shows all the important stuff.

And yes, I've tried swapping the cabinets around.

**Comment by Filostorm** [comment]
You don't have a server paper in your server (I don't recall the exact name of the item)

**Comment by m-yst-ery** [comment]
Does that matter if the server is turned off?

And the alloyer also did not work without a server being attached. Or is the server required for this structure?

**Comment by Filostorm** [comment]
Shouldn't matter if the server is turned off, no. It's also not required, in fact I don't recommend ever using one tbh. 

I do think your cabinets are in the wrong order though, can you send a screenshot of the manual as well?

**Comment by m-yst-ery** [comment]
Ok, yeah no you're right
I tried swapping them around multiple times, but apparently I've always succesfully failed at remembering how I put them up before ;-;

Thanks for the help ^^'

**Comment by Filostorm** [comment]
Awesome, no problem. 

I'd like to update the mod but really don't feel like fixing everything in the pack that would be broken lol.
