### ISSUE TITLE
Multiblock Madness (Requests)

### ISSUE THREAD

**Issue by lawfulrocky** [Filostorm/Multiblock-Madness#2]
Please all mod requests should go here so that we dont have multiple issue open for it

**Comment by P3R5I4N** [comment]
Hello, I am looking to revert some of the vanilla recipes in this pack to make it more accessible to some friends who will be playing on a server with me. I am in particular having trouble figuring out which config file affects these recipes as well as how to reenable vanilla tools. Any assistance would be greatly appreciated.

**Comment by TheMoonOfMan** [comment]
I have found a rather easy skip in progression. Once you get the melter and the equipment needed for it you can melt down "The Ender" sword and get dark steel, effectively skipping all tool progression that is in the pack and having a tier 4 tool to which you can go get cobalt and so on. Like i said this is super easy and hence why i am making this request. Hope this has helped. btw love the pack

**Comment by Filostorm** [comment]
Appreciate the report, I can remove the melting recipe for the Ender. Mining progression is meant to be more a separate challenge that you can do multiple ways, so it’s not as big of an issue though. 

Thank you!
