### ISSUE TITLE
Crashes on startup and other random crashes

### ISSUE THREAD

**Issue by leyxcx** [Filostorm/Multiblock-Madness#22]
Installed this pack just now and created two worlds, both crashed on startup and then when I went back into one world it worked for a minute or two and then crashed again.

[crash-2021-04-11_17.22.35-server.txt](https://github.com/Filostorm/Multiblock-Madness/files/6291221/crash-2021-04-11_17.22.35-server.txt)

![ddsfd](https://user-images.githubusercontent.com/67163463/114293549-24c7d480-9aeb-11eb-830b-614b2f49889b.png)

**Comment by Filostorm** [comment]
Try uninstalling apotheosis, looks like it is causing problems on world gen for you. 

You could also try reinstalling the pack, it’s possible something didn’t download properly.

**Comment by leyxcx** [comment]
Reinstalled the pack and it seems to be working ok now, I'll let you know if I run into the issue again

**Comment by leyxcx** [comment]
well, I spoke too soon lmao. It crashed as soon as I was around sky stone oddly, I've removed apotheosis for now.

**Comment by Filostorm** [comment]
We found the issue, it’s unfortunate but adding the new boss mobs is causing all sorts of problems. One person had a Naga head following him around his base lol. Easy fix though, I’ll probably release a patch tonight

**Comment by Filostorm** [comment]
Update your pack to 1.0.2 to fix. Thanks for the report!
