### ISSUE TITLE
Game Randomly Crashing Possibly Due to Apotheosis or Placebo

### ISSUE THREAD

**Issue by SlimGrim602** [Filostorm/Multiblock-Madness#23]
The game randomly crashes and tells me that it might be because of Apotheosis or Placebo. I have attached a crash log from the crash.

[crash-2021-04-11_00.09.49-server.txt](https://github.com/Filostorm/Multiblock-Madness/files/6292071/crash-2021-04-11_00.09.49-server.txt)

**Comment by Filostorm** [comment]
Will be fixed in the next update, hopefully tonight

**Comment by Filostorm** [comment]
Update your pack to 1.0.2 to fix. Thanks for the report!
