### ISSUE TITLE
[1.0.3] Recipe missing/confilct

### ISSUE THREAD

**Issue by SteveClover** [Filostorm/Multiblock-Madness#34]
I am trying to make the Low-gravity Deposition Chamber multiblock and have found 3 issues in the quest:

1) The quest requires 32 Scal scaffolding from JAOPCA, but the only recipe for Scal scaffolding is from ContentTweaker
2) There is no crafting recipe for the Biome Detector
3) The quest calls for 24 Nimonic sheetmetal form JAOPCA which has no recipe (there is a recipe for Nimonic sheetmetal from ContentTweaker)

**Comment by Filostorm** [comment]
Ah, I see the issue. Will be fixed

**Comment by Filostorm** [comment]
Fixed in 1.0.4
