### ISSUE TITLE
Items vanish occasionally on any block drop event while playing on a dedicated server.

### ISSUE THREAD

**Issue by IIIpl4sm4III** [Filostorm/Multiblock-Madness#37]
Items occasionally vanish when mining, killing, etc that would normally produce an item drop. The item will visually drop instantly, but vanish shortly after. 
[Video of this on Version 1.0.4](https://streamable.com/rqpn4i)
An easy way to replicate this is to run around and break sugar cane, or flowers, or any block with a 100% drop-rate. 
A proposed solution is to relog, however this neither makes the item return or the block/animal to reappear. 
I have tested this on a private dedicated server as well as the current public one included in the multiplayer list. Players on the public server reported this happening as well.

**Comment by Filostorm** [comment]
Is it gone for good? Or can you still pick up the invisible item?

**Comment by IIIpl4sm4III** [comment]
> Is it gone for good? Or can you still pick up the invisible item?

From the initial incident, they seem to be completely gone, even after a re-log.
I found that it happens more often when the server is skipping ticks or is low on TPS (I.e. exploring)
Since adding some additional java cleanup arguments on the server end, I haven't seen it happen since.

**Comment by IIIpl4sm4III** [comment]
Happened again, rarer now that the server isn't overloaded. The items do vanish, and don't return after a re-log.

**Comment by Filostorm** [comment]
That's very odd. I'll look into it.

**Comment by Filostorm** [comment]
Still not sure why this was an issue, but haven't had anyone else with the same problem so I'll close it for now
