### ISSUE TITLE
Rock Crystals Not Found

### ISSUE THREAD

**Issue by tpaukovi** [Filostorm/Multiblock-Madness#4]
Are rock crystals from Astral Sorcery actually enabled in the ore gen?

Based on astralsorcery.cfg, they are disabled:
        # Generate rockcrystals [default: true]
        B:Generate=false

Now, there could be custom gen somewhere, but I don't know how to find that =)
I tried looking at the "orespawn" files, but didn't see any mention of them there.

I've tried using the resonating wand to locate them, but that doesn't work (even if I place them in creative).
I've tried clearing out dozens of chunks worth of blocks near bedrock, but found none that way either.
Am I wasting my time?

**Comment by Filostorm** [comment]
Astral Rock Crystals do spawn, they are in deep coal veins between Y levels 0-20.

Config is located at: \config\cofh\world/05_new_ore_gen.json.

**Comment by Filostorm** [comment]
![2021-02-20_00 22 52](https://user-images.githubusercontent.com/73716145/108584765-e0516100-7311-11eb-9572-01be2ff80a8b.png)

Looks like this

**Comment by tpaukovi** [comment]
Ah, cool. I've found those, but can't mine diamond yet, so maybe it's stuck inside.
Thanks!

**Comment by Filostorm** [comment]
No problem, thanks for the report! I'm looking into why Rockcrystal ore doesn't glow.

**Comment by tpaukovi** [comment]
My guess is the glow is tied to the default ore gen, marking the locations as it generates chunks.
Since that's disabled, nothing is "marked" along the way.
No idea if it's possible to hook into that in "configuration" without it being built into to the custom ore gen mod (or maybe do a post-gen scan).

**Comment by Filostorm** [comment]
Seems to be the case. I’m testing turning it back on, as well as keeping the crystals in the deep ore veins
