### ISSUE TITLE
Crashes from Immersive Petroleum Core Samples

### ISSUE THREAD

**Issue by EndearinglyConfused** [Filostorm/Multiblock-Madness#40]
Whenever I would hover over a core sample either in the world or in my inventory, there was a crash attributed to the Immersive Engineering mod. I was a fool and forgot to save the crash log, but it only seemed to happen on _some_ rather than all of the core samples. This is also just since the newest update.

**Comment by Filostorm** [comment]
It's a know bug with existing samples that contain water. Add [this](https://github.com/Filostorm/Multiblock-Madness/files/6448711/immersivepetroleum.zip) to your config folder after you unzip it. That will re-enable the water reservoir, so you can remove those samples in your world.

**Comment by EndearinglyConfused** [comment]
Awesome, thank you so much! I already did get rid of the samples through some Quark iron rod & piston trickery, but hopefully this way I can use the excavator with a little less concern
