### ISSUE TITLE
Actually Additions AIOT tools do not show up in JEI

### ISSUE THREAD

**Issue by Rodnock** [Filostorm/Multiblock-Madness#50]
I was looking at the uses for a diamond sword and noticed that the AIOT is listed as an option. When searching for AIOT or @ActuallyAdditions in JEI, no AIOT shows. See attached imgur link for pictures.

https://imgur.com/a/fGTLTE0

Edit: I should note this is on v1.0.4

**Comment by Filostorm** [comment]
You already saw on discord, but I'm planning on unhiding the recipes from jei. That was an old decision from when I was going through cleaning up extra stuff
