### ISSUE TITLE
Pulsating Iron sheetmetal not craftable

### ISSUE THREAD

**Issue by omglolbah** [Filostorm/Multiblock-Madness#53]
Using 1.1.0

Pulsating iron sheetmetal not craftable as far as I can tell.
It is required to make Soot-covered Machine Frame and thus blocks progress to Mob Agonizer.

**Comment by Filostorm** [comment]
Thanks, I'll see if I can get a quick patch out for it

**Comment by Filostorm** [comment]
Fixed in 1.1.1, but I'll leave it open for a bit just incase someone else has the same issue
