### ISSUE TITLE
simple machine chassis parts uncraftable

### ISSUE THREAD

**Issue by chainblade131** [Filostorm/Multiblock-Madness#56]
I'm using version 1.1.1 working with EnderIO's inventory storage system and cannot find a recipe for the simple machine chassis parts. In fact I cant find anything about these parts online or the EnderIO wiki at all, besides the regular machine chassis parts.

**Comment by Filostorm** [comment]
I can add a recipe for those

**Comment by Filostorm** [comment]
Will be added in 1.1.2
