### ISSUE TITLE
Agricraft village houses can choose ANY SEED to spawn.

### ISSUE THREAD

**Issue by NerdySpider** [Filostorm/Multiblock-Madness#58]
Hi there! I found a ''small'' issue with the village house Agricraft spawns, it spawns a small greenhouse, alongside a bunch of crop sticks, the problem is, within these crop sticks it can choose ANY seed, this includes Mystical Agriculture ones.
I'm not sure if this is intentional, but just in case, I wanted to let this issue be known! 
![image](https://user-images.githubusercontent.com/29170640/120755425-4e343800-c551-11eb-9a0b-58f576d87c35.png)

![image](https://user-images.githubusercontent.com/29170640/120755385-42487600-c551-11eb-8a39-623774a1a6f4.png)

**Comment by Keilay** [comment]
Yeah same for me i literaly got every single mystical seed after looting about 4 villages.

**Comment by Filostorm** [comment]
Wow, that's pretty broken. Config says that the max tier seed is 3, can you confirm that?

**Comment by NerdySpider** [comment]
> Wow, that's pretty broken. Config says that the max tier seed is 3, can you confirm that?

This can't be correct only because I got tier 3+ seeds, such as iridium. So I'm pretty sure it didn't follow it? I can't be too sure though.

**Comment by Filostorm** [comment]
I wonder where it's pulling that number from then. 

I'll change it to 1 for now, but keep me posted if you find any new ones with high tier seeds after the next update drops.

**Comment by NerdySpider** [comment]
> I wonder where it's pulling that number from then.
> 
> I'll change it to 1 for now, but keep me posted if you find any new ones with high tier seeds after the next update drops.

Sure thing :)

**Comment by Keilay** [comment]
A bit late, but i just checked in my config and its actualy set up on tier 3 for the Agricraft greenhouse which is weird because i definitly got uranium / void / terrasteel seeds and such in thoose. + I also saw the config says it sould be 1 greenhouse max per village but i found villages with 2 greenhouses, might help.

**Comment by Filostorm** [comment]
I'm just going to remove them from villages. At least until they fix their config

**Comment by Filostorm** [comment]
I asked the Agricraft people if they would be willing to change it, we'll see
