### ISSUE TITLE
Shrinker device fail from capsule

### ISSUE THREAD

**Issue by Dragon87tamer** [Filostorm/Multiblock-Madness#64]
the config files for the compactmachines-shrinker.json or compactmachines-shrinker2.json is wrong. Needs "id": "immersiveengineering:sheetmetal", Changed to "jaopca:block_sheetmetalsilver" Due to the fact the capsules spawn with Jaopca silver sheet metals. Yet both jsons use immersive sheet metal!

**Comment by Filostorm** [comment]
Fixed by removing that capsule. As a one time craft it seemed unneeded.
