### ISSUE TITLE
Minecraft keeps on getting stuck on launch - Finishing Up 6/7 - CraftTweaker2 29/309

### ISSUE THREAD

**Issue by k00lk4t** [Filostorm/Multiblock-Madness#65]
Title says it all. I cant launch Multiblock Madness because it always gets stuck at the same stage. Ive tried giving it 9gb ram, 8gb ram, 7gb ram and even a clean install but nothing works. I'd just like to play this pack.

**Comment by Filostorm** [comment]
Did you ask this on the discord as well? Switching launcher solved it?

**Comment by k00lk4t** [comment]
Yes switching to another launcher worked but id dont understand why it
didnt work with multimc

**Comment by Filostorm** [comment]
I'm not sure either, it normally works fine on MultiMC

**Comment by akasia** [comment]
fine for me at MultiMC
