### ISSUE TITLE
why i can't make sodium hydroxide form rockhouding using mek Brine 

### ISSUE THREAD

**Issue by akasia** [Filostorm/Multiblock-Madness#66]
why i can't make sodium hydroxide form rockhouding using mek Brine that jei show that i can make it from mek Brine  but valid recipe
![2021-06-24_16 53 55](https://user-images.githubusercontent.com/14824981/123233673-d41e2000-d50c-11eb-9d98-8df6c067cd13.png)
![2021-06-24_16 53 42](https://user-images.githubusercontent.com/14824981/123233688-d7191080-d50c-11eb-8930-42b58c92cb98.png)
![2021-06-24_16 53 41](https://user-images.githubusercontent.com/14824981/123233703-d97b6a80-d50c-11eb-91ac-75ca30fd85ae.png)
![2021-06-24_16 53 35](https://user-images.githubusercontent.com/14824981/123233713-dbddc480-d50c-11eb-86dc-5589b12be14f.png)
![2021-06-24_16 53 32](https://user-images.githubusercontent.com/14824981/123233728-e009e200-d50c-11eb-8655-1882c095080d.png)

**Comment by akasia** [comment]
and 1 more thing why i ca't filter using samplng ampoule every time i filter it when i close inventory it turn to other fluid?is that a bug? 
![2021-06-24_18 48 59](https://user-images.githubusercontent.com/14824981/123250662-e86a1900-d51c-11eb-8af5-7c4d8ff9f8aa.png)
try to filter water
![2021-06-24_18 49 02](https://user-images.githubusercontent.com/14824981/123250696-f28c1780-d51c-11eb-900e-9bd5bde9255e.png)
sampleshow filter water
![2021-06-24_18 49 10](https://user-images.githubusercontent.com/14824981/123250744-fe77d980-d51c-11eb-9cee-f5b7c140c3c0.png)
close inventory gui 
![2021-06-24_18 49 10](https://user-images.githubusercontent.com/14824981/123250772-09cb0500-d51d-11eb-849c-f7201f3da402.png)
reopen it Congratulationsyou has filted arcylic acid
![2021-06-24_18 49 15](https://user-images.githubusercontent.com/14824981/123250932-354def80-d51d-11eb-9010-07e1a07a4514.png)

**Comment by Filostorm** [comment]
The last issue is because using the letters is bugged. You need to use the arrows

**Comment by Filostorm** [comment]
Join our [discord](https://discord.gg/mY52ZW6dZd) for better help with issues like this, I'm not able to be on all the time
