### ISSUE TITLE
invalid agricraft parents for botania:white_flower_plant

### ISSUE THREAD

**Issue by nekizalb** [Filostorm/Multiblock-Madness#67]
The mutations for the botania white plant is invalid. It should reference vanilla:wheat_plant and vanilla:melon_plant. The vanilla prefix is missing

mutation file:
https://github.com/Filostorm/Multiblock-Madness/blob/master/config/agricraft/json/defaults/mod_botania/mutations/botania_white_mutation.json

see corrected file in AgriPlants repo:
https://github.com/AgriCraft/AgriPlants/blob/1.12.2/mod_botania/mutations/botania_white_mutation.json

log file:
[00:13:12] [Client thread/INFO]: Invalid Mutation: Invalid Parent 1: "wheat_plant"!

Mutation:
	- Parents:
		- Parent 1: wheat_plant
		- Parent 2: melon_plant
	- Child: botania:white_flower_plant
	- Chance: 0.5

[00:13:12] [Client thread/INFO]: Invalid Mutation: Invalid Parent 2: "wheat_plant"!

Mutation:
	- Parents:
		- Parent 1: botania:white_flower_plant
		- Parent 2: wheat_plant
	- Child: botania:yellow_flower_plant
	- Chance: 0.5

**Comment by nekizalb** [comment]
It also appears you've accidentally gotten a copy of botania's mutations and soils mixed in with mystical world folder, duplicating them

https://github.com/Filostorm/Multiblock-Madness/tree/master/config/agricraft/json/defaults/mod_mysticalworld/mutations

**Comment by Filostorm** [comment]
It's honestly weird how much I've had to do to get agricraft working

**Comment by shawn1368** [comment]
Botania white petal seeds now have their own custom recipe in the TC cauldron, so it should be fixed now.
