### ISSUE TITLE
Unable to craft Machine Controller from Modular Machines

### ISSUE THREAD

**Issue by rptbuddy** [Filostorm/Multiblock-Madness#70]
Recipe requires insulated gold cables which are produced in the multiblock.   Tech Reborn assembler no longer works.

Tech Reborn Electronic Circuit is also uncraftable

Version: 1.2.0 Beta

**Comment by rptbuddy** [comment]
Nvm Tech Reborn Electronic Circuit is craftable my machine was gummed up with gold wires.  It seems only the different scaffoldings and the gold cables are currently not craftable in the tech reborn assembler when previously they were.

**Comment by Filostorm** [comment]
Thanks for the report, I'll be changing the advanced coil in the recipe!
