### ISSUE TITLE
1.2.0 uncraftable lightwell

### ISSUE THREAD

**Issue by PLDO001** [Filostorm/Multiblock-Madness#72]
Luminous crafting table don't recognize lightwell recipes

![2021-08-17_08 57 32](https://user-images.githubusercontent.com/20399618/129679023-f6e690b5-5374-4ba7-8aad-a6d3da9aacf9.png)
![2021-08-17_08 58 23](https://user-images.githubusercontent.com/20399618/129679032-8cf06ee4-6fe4-4af5-88d6-66d57d8f1722.png)

**Comment by Filostorm** [comment]
This is because of the missing research. Either claim the quest, which unlocks it for you, or craft the altar under the floating crystal
