### ISSUE TITLE
Circuit blueprint recipe missing 

### ISSUE THREAD

**Issue by Libellchen** [Filostorm/Multiblock-Madness#73]
Can't find the recipe for the circuit blueprint, which seems to be needed for the electronic circuit. You need it to craft the basic machine frame. So I'm currently stuck at the beginning of chapter 5. 

![Blueprints](https://user-images.githubusercontent.com/89144106/129957466-54431869-458f-4f1f-b89c-06b869bc6847.png)

![Blueprints](https://user-images.githubusercontent.com/89144106/129958278-b14ea5de-ae77-4445-b6ff-b8f4f51c4b69.png)

It's part of the JEI. If you click it the recipe for ever blueprint but this one opens.

**Comment by Filostorm** [comment]
Will be fixed in the next update. For now if you mouse over the correct blueprint in jei and bookmark it, you can use cheat mode to get one

**Comment by Libellchen** [comment]
Playing on a server unfortunately. So, we'll have to wait. Thanks for the quick reply. ^-^

**Comment by Filostorm** [comment]
No problem, it should be finished this week

**Comment by Filostorm** [comment]
Update is out!
