### ISSUE TITLE
Primal Crusher cannot be used to mine

### ISSUE THREAD

**Issue by alphaNumeric01** [Filostorm/Multiblock-Madness#75]
It seems that the mining level of the Primordial crusher has been set to something less than 0. Normally it should be able to mine in a 3x3 area, but it seems to be completely unable to even mine any sort of block without destroying it completely as if it can't be used for mining. 

Is this intentional?

**Comment by Filostorm** [comment]
Not intended, changed to level 5 in 1.2.2 (not yet released) Thanks!
