### ISSUE TITLE
Quests not completing & missing recipe

### ISSUE THREAD

**Issue by Libellchen** [Filostorm/Multiblock-Madness#76]
Version 1.2.1 & 1.2.0 (Can't say if this is also a problem in the 1.2.2 version)

The Rockhounding Chapter is not accepting all the needed items. 

![2021-09-02_08 43 04](https://user-images.githubusercontent.com/89144106/131797018-230935e5-b020-4868-8089-01499b5fa590.png)
As you can see the the fluidpedia is definitely in my hotbar. I also tried to place it and pick it up again but nothing seems to work. 
Have the same problem for the following two quests and i can't make progress in the chapter. Even though I already progressed  to the leaching vat without the quest book.

![2021-09-02_08 43 33](https://user-images.githubusercontent.com/89144106/131797230-18359da6-7f8a-403f-b052-1bb27665ce0e.png)

![2021-09-02_08 43 46](https://user-images.githubusercontent.com/89144106/131797235-f9cfd2ac-d7ef-4ddb-93e9-a97bb10aa89f.png)
---------------------

Version 1.2.2

It's probably easy to fix bit I don't know how. ^^

![image](https://user-images.githubusercontent.com/89144106/131798669-e4690616-802c-4a4f-a669-f0c136efdaba.png)

![image](https://user-images.githubusercontent.com/89144106/131798728-6963c896-bd3a-4070-bcb3-fb58249155df.png)

**Comment by Filostorm** [comment]
Thanks for the notice! Yes, that's a simple fix, I just need to change the quest to accept and nbt data on the items.

For now, if you are able to cheat in one of the items from JEI, that will allow you to progress.
