### ISSUE TITLE
Cyclic Forester doesn't work? Quest book recommends using it.

### ISSUE THREAD

**Issue by toastonrye** [Filostorm/Multiblock-Madness#77]
Pack version 1.2.0

I've tried removing my FTBUtils chunk claiming. I power the Forester and it runs and continuously uses power but it doesn't plant any saplings in its inventory. There is a lot of room around it.

**Comment by toastonrye** [comment]
Apparently, it can't be in the ground, it has to be above. And it seems to be limited to only placing a few saplings.

**Comment by Filostorm** [comment]
I removed my recommendation for using the forester in later versions because it's so finicky. 

Bonsai leaf output has been buffed, so combining a few with a placer works well. 

There is also a wood cutting machine in engineers decor that works pretty well

**Comment by toastonrye** [comment]
Ok good to know, I should update the pack today. I've actually been messing around with it again this morning and figured out its quirks, and my setup is working well.

I do actually have a couple of those bonsai hopper bots setup, I just wasn't sure the best way to use them with Botania's Munchdew. A large block placing array? The RFTools Builder would be epic, but that's not early game lol!

**Comment by Filostorm** [comment]
Pretty sure the openblocks placer works fast enough to keep up. Feel free to join the discord for general questions and tips!
