### ISSUE TITLE
Blank Rune quest

### ISSUE THREAD

**Issue by million09** [Filostorm/Multiblock-Madness#78]
Quest No.153 (Tier 2 Blood Altar / Blank Runes) has two requisites; No.206 (The Crusher) and No.211 (Squeezer). They are combined with OR, but should be AND, as Blank Runes require both machines.

**Comment by Filostorm** [comment]
Good catch, I'll fix that

**Comment by Filostorm** [comment]
Fixed in upcoming 2.0.0
