### ISSUE TITLE
Super Sound Muffler Causes an Unknown Problem alert

### ISSUE THREAD

**Issue by toastonrye** [Filostorm/Multiblock-Madness#79]
When I place to super sound muffler a "toast" popup from Minecraft says an unknown problem occurred. And it spams my game till I reload.

**Comment by Filostorm** [comment]
I don't think there is something I can do about that issue, but you can go into vanillafix.cfg and change the line 
   "I:errorNotificationDuration=" to 1. I'll also be changing that for future versions.
