### ISSUE TITLE
Farmer Quest - Suggest adding more details to quest, to warn players about losing seed stats

### ISSUE THREAD

**Issue by toastonrye** [Filostorm/Multiblock-Madness#80]
Apologies if this has been fixed, but I didn't see anything here relating to the Farmer. I'm on v1.2.3
The Farmer quest says "Automatic 9x9 farming, pairs well with crop sticks"

I started growing the Agricraft version of canola and a couple Thaumcraft seeds and breeding up the stats. However, I accidentally clicked on fertile dirt with no cropsticks and quickly learned that deletes the Agricraft stats.

The next issue was using the Farmer block, I made sure to put all the cropsticks down first, thinking I don't want to lose my seed stats again. I put the seed into the farmer and it automatically places the seed with the cropsticks, deleting the stats. I learned you have to manually place the seed in the cropsticks.

I suggest 2 warnings:
1. Do not put Agricraft type seeds down without cropsticks, it voids the stats and you restart at 1/1/1
2. Do not let the Farmer place the Agricraft type seeds, it will void the cropstick and place the seeds, voiding the stats to 1/1/1

Always place Agricraft type seeds in cropsticks, always manually plant the seeds infront of the Farmer.

**Comment by Filostorm** [comment]
Good idea, I'll add that to the quest
