### ISSUE TITLE
Recipes Issues

### ISSUE THREAD

**Issue by NotZerby** [Filostorm/Multiblock-Madness#81]
Pack version: 2.0.0 beta 2 

I noticed that a lot of items have "double recipes" (the default recipe and the craftweaker one), some of them are: IE engineering blocks, generator and radiator blocks, IE blast bricks (i thought they were not implemented), and improved blast bricks, modularium, machine frames from various mods, blood altar and ME controller. 
Other blocks from Tinker i/o like the ore crusher, have been implemented and I thought they were not.
And lastly, the translocators have only the normal recipe.

I know it's a beta, so it may have a few missing pieces, but I think that feedback could be appreciated.

**Comment by Filostorm** [comment]
Yep, that's caused by an unfortunately simple oversight. 

You can fix it yourself by opening Non Mod Scripts\add-recipes-temp.zs and search for addMirrored, then change it to addShapedMirrored.
