### ISSUE TITLE
Cannot deploy Thermal Steel Block from capsule

### ISSUE THREAD

**Issue by million09** [Filostorm/Multiblock-Madness#83]
When trying to deploy `ie-arcfurnace` (and probably others) capsule, I'm warned 6x Block of Steel are missing, though I have Steel Block from Thermal Foundation in my inventry.

**Comment by Filostorm** [comment]
Known issue, I've asked the capsule dev to add a fix. Until then you can chisel the blocks into the correct modes version

**Comment by Filostorm** [comment]
I was able to edit the nbt for the blueprints to swap the blocks out, fixed in upcoming version 2.0.0

**Comment by million09** [comment]
Oh, I overlooked Lythom/capsule#48.
