### ISSUE TITLE
crash while looking through recipes in JEI

### ISSUE THREAD

**Issue by donoya** [Filostorm/Multiblock-Madness#88]
[hs_err_pid6156.log](https://github.com/Filostorm/Multiblock-Madness/files/7316377/hs_err_pid6156.log)
The error occurred while moving the mouse cursor off of an item in the recipe. The recipe was one of the rockhounding machine recipes. I do not know if it'd happen every time, yet. It happened pretty early into making the world.

**Comment by donoya** [comment]
[latest.log](https://github.com/Filostorm/Multiblock-Madness/files/7316381/latest.log)
And here's the log in case you need it.

**Comment by Filostorm** [comment]
Haven't heard of either of these happening before

**Comment by Filostorm** [comment]
Closing because it seems isolated
