### ISSUE TITLE
random crash while mining fossils

### ISSUE THREAD

**Issue by donoya** [Filostorm/Multiblock-Madness#90]
[hs_err_pid4540.log](https://github.com/Filostorm/Multiblock-Madness/files/7318313/hs_err_pid4540.log)
[replay_pid4540.log](https://github.com/Filostorm/Multiblock-Madness/files/7318314/replay_pid4540.log)
[latest.log](https://github.com/Filostorm/Multiblock-Madness/files/7318315/latest.log)

**Comment by Filostorm** [comment]
Closing because it seems isolated
