### ISSUE TITLE
No text in the buttons on the main menu

### ISSUE THREAD

**Issue by seitenca** [Filostorm/Multiblock-Madness#91]
![image](https://user-images.githubusercontent.com/55158851/137992981-883e87d1-54f7-473b-b5bc-ac33ede62e09.png)
Is this a known issue? Or it's been fixed already? I on the latest on Curseforge (2.0.0)

**Comment by seitenca** [comment]
ok I found the problem, just what i thought
In [multiblockmadness.txt](https://github.com/Filostorm/Multiblock-Madness/blob/master/config/fancymenu/customization/multiblockmadness.txt) there is paths that have "\\" and should be "/" to work on Linux

**Comment by Filostorm** [comment]
Yes, it's come up a few time, but I really appreciate you taking the time to look into fixing it! I'll fix it in the next version

**Comment by Filostorm** [comment]
Fixed in 2.0.1
