### ISSUE TITLE
Recipes Issues (Ender Alloy (Advanced), Glitch Boots)

### ISSUE THREAD

**Issue by mfkG** [Filostorm/Multiblock-Madness#92]
Modpack v2.0.0 (updated from beta..)

I have no recipe for Ender Alloy (Advanced), so i can't progress and make the "Mana Infused Ingot" (or i have no clue how i should do).

And the boots and Helmet from the Glitch Armor Set have the same recipies.

**Comment by Filostorm** [comment]
Fixed in 2.0.1
