### ISSUE TITLE
question about IT-SteamTurbine

### ISSUE THREAD

**Issue by plcyc2333** [Filostorm/Multiblock-Madness#98]
SteamTurbine in Immersive Tech consume 3150 mb/t steam. Are you serious??
Even I use Elite Mechanical Pipe（MEK）and Creative Fluid Tank（MEK）cannot activate the SteamTurbine.
And the Boiler has same problem, how can I input 3150 mb/t water????
the version is 2.0.3(newest)

I found your setting in scripts/Non Mod Scripts/power.zs
this line:
 mods.immersivetechnology.SteamTurbine.addFuel(<liquid:exhauststeam> * 3150, <liquid:steam> * 3150, 1);
I guess you mistook the unit of time as "second", but it's actually "tick".
If I wrong, forget this.

**Comment by Filostorm** [comment]
I'll look into this, thanks for the report!

**Comment by Filostorm** [comment]
IT has had a major update and is almost completely reworked. Because of this, steam power is reverted back to defaults until we're able to look into rebalancing it.
